src = ["src"]
exclude = ["docs/source", ".git"]
line-length = 120

lint.select = [
    "F", "C", "E", "R", "W", "C90", "I", "N", "D", "UP", 
    "YTT", "BLE", "B", "A", "COM", 
    "C4", "DTZ", "T10", "EM", "FA", "ISC", "ICN", 
    "LOG", "G", "INP", "PIE", "T20", "PYI", "PT", "RSE", 
    "RET", "SLF", "SLOT", "SIM", "TID", "TCH", "INT", "ARG", "TD", 
    "C901"
]
lint.ignore = ["E501", "G004", "LOG015"]

[lint.pydocstyle]
convention = "numpy"

[lint.per-file-ignores]
"src/*" = ["D", "N806", "N802", "C901", "SLF001", "ARG004", "ARG002", "ARG001"]
"examples/*" = ["D", "INP001", "ARG"]
"app/main.py" = ["A002","D103","DTZ005","D100","INP001"]
"tests/*" = ["ALL"]

[format]
quote-style = "single"
indent-style = "space"
skip-magic-trailing-comma = false
docstring-code-format = true
docstring-code-line-length = "dynamic"
