[project]
name = "acoupipe"
version = "23.1"
description = ""
readme = "README.rst"
requires-python = ">=3.7,<11"

[tool.ruff]
src = ["src"]
ignore = [
    "D100", "D101", "D102", "D103", "D105", "D107",
    "D203", "D213", "D206",
    "B905",
    "N806", "N803",
    "E741"]
line-length = 120
select = ["B", "D", "E", "F", "I", "N", "Q", "W"]


