name: Build and Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
    branches: [ "*" ]

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-13, windows-latest]
        python-version: ['3.10','3.11']

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install base 
      run: |
        python -m pip install --upgrade pip
        pip install .
        python -c 'import acoupipe'
    - name: Install full 
      run: |
        python -m pip install --upgrade pip
        pip install ".[full]"
        python -c 'import acoupipe'
    - name: Install dev 
      run: |
        python -m pip install --upgrade pip
        pip install ".[dev]"
        python -c 'import acoupipe'    
    - name: Tests (unix) 
      run: |
        chmod +x ../acoupipe/tests/run_tests.sh
        cd ../acoupipe/tests/
        bash run_tests.sh
      if: ${{ matrix.os != 'windows-latest'}}
    - name: Tests (windows)
      run: |
        cd ../acoupipe/tests/
        python -m unittest discover -v -p "test_*.py"
      if: ${{ matrix.os == 'windows-latest'}} 

