name: DockerHub Continous Integration

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Login to docker 
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PWD: ${{secrets.DOCKER_PASSWORD}}
      run: 
        docker login -u $DOCKER_USER -p $DOCKER_PWD 
    - name: Build image
      run: docker build . --file Dockerfile --tag acoupipe:latest
    
    - name: Push to DockerHub
      run: docker push ${{secrets.DOCKER_USER}}/acoupipe:latest
