name: AcouPipe 🎵 Organizational CI
permissions:
  contents: read
on:
  pull_request:
    branches: [ master, dev ]

jobs:
  coverage:
    uses: acoular/ci/.github/workflows/coverage.yml@main
    permissions:
      contents: read
      pull-requests: write
    with:
      src_dir: "src/acoupipe"
      setup_portaudio: false

  tests:
    uses: acoular/ci/.github/workflows/tests.yml@main
    with:
      src_dir: "src/acoupipe"
      setup_portaudio: false
      
  docs:
    uses: acoular/ci/.github/workflows/docs.yml@main
    with:
      setup_portaudio: false

  github:
    uses: acoular/ci/.github/workflows/github.yml@main

  linting:
    uses: acoular/ci/.github/workflows/linting.yml@main

  links:
    uses: acoular/ci/.github/workflows/links.yml@main
    with:
      extra_args: "--exclude http://0.0.0.0:8265/ --exclude https://slurm.schedmd.com/"