# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    - name: Install base 
      run: |
        python -m pip install --upgrade pip
        pip install .
        python -c 'import acoupipe'
    - name: Install full 
      run: |
        python -m pip install --upgrade pip
        pip install ".[full]"
        python -c 'import acoupipe'
    - name: Install dev 
      run: |
        python -m pip install --upgrade pip
        pip install ".[dev]"
        python -c 'import acoupipe'    
    - name: Tests 
      run: |
        chmod +x ../acoupipe/tests/run_tests.sh
        cd ../acoupipe/tests/
        bash run_tests.sh
